[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production"

[deploy]
startCommand = "cd backend && node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"